version: '3.8'
services:
  ros2:
    container_name: ros2-container
    image: ros2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DISPLAY: $DISPLAY
      QT_X11_NO_MITSHM: '1'
      TURTLEBOT3_MODEL: burger
    stdin_open: true
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority
      - /home/niklas/ros_2/src:/root/ros2_ws/
      - /home/niklas/ros_2/history/.bash_history:/root/.bash_history
    tty: true
    command: tail -f /dev/null

